name: Lint

on:
  # Trigger the workflow
  push:
    branches:
      - "production"
  pull_request:
    branches:
      - "production"
  workflow_dispatch:

jobs:
  run-linux-build:
    name: Run Linux build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.7

      - name: Install Python dependencies
        run: pip install -r dev/requirements.txt

      - name: Build python executable
        run: yarn python:build

      - name: Build App
        run: yarn electron:build-release
